/**
 * Alle deutschen UI-Strings zentral — der Tisch-Jargon (deutsche Labels,
 * englische Regelbegriffe wie in der Gruppen-Excel) ist hier einstellbar.
 */
export const S = {
  appName: "Chardex35",

  nav: {
    characters: "Charaktere",
    compendium: "Kompendium",
    dice: "Würfel",
    settings: "Einstellungen",
  },

  abilities: {
    str: "ST",
    dex: "GE",
    con: "KO",
    int: "IN",
    wis: "WE",
    cha: "CH",
  } as Record<string, string>,
  abilityNames: {
    str: "Stärke",
    dex: "Geschicklichkeit",
    con: "Konstitution",
    int: "Intelligenz",
    wis: "Weisheit",
    cha: "Charisma",
  } as Record<string, string>,

  saves: { fort: "Fortitude", ref: "Reflex", will: "Will" } as Record<string, string>,

  sheet: {
    tabs: {
      stats: "Werte",
      combat: "Kampf",
      skills: "Fertigkeiten",
      spells: "Zauber",
      inventory: "Ausrüstung",
      feats: "Talente",
      notes: "Notizen",
    },
    /** Kurzformen für die mobile Reiter-Leiste (sieben Reiter nebeneinander). */
    tabsShort: {
      stats: "Werte",
      combat: "Kampf",
      skills: "Fert.",
      spells: "Zauber",
      inventory: "Ausr.",
      feats: "Talente",
      notes: "Notiz",
    },
    hp: "TP",
    hpMax: "max.",
    damage: "Schaden",
    nonlethal: "Nichttödlich",
    temp: "Temp. TP",
    ac: "RK",
    touch: "Touch",
    flatFooted: "Flat-Footed",
    init: "Initiative",
    speed: "Bewegung",
    bab: "GAB",
    grapple: "Ringkampf",
    level: "Stufe",
    xp: "EP",
    nextLevel: "nächste Stufe",
    attacks: "Angriffe",
    damage2: "Schaden",
    critical: "Krit.",
    ranks: "Ränge",
    maxRanks: "max.",
    classSkill: "Klassenfertigkeit",
    melee: "Nahkampf",
    ranged: "Fernkampf",
    equipped: "Angelegt",
    stowed: "Rucksack",
    skillFilter: { all: "Alle", trained: "Trainiert", class: "Klasse" } as Record<string, string>,
    subtype: "Teilgebiet",
    addSubtype: "Teilgebiet anlegen",
    subtypePrompt: "Teilgebiet (z.B. arcana, weaponsmithing):",
    conditions: "Zustände",
    features: "Klassenfähigkeiten",
    miscMods: "Sonstige Modifikatoren",
    encumbrance: { light: "Leichte Last", medium: "Mittlere Last", heavy: "Schwere Last", overloaded: "Überladen!" } as Record<string, string>,
    slots: "Slots",
    dcBase: "SG-Basis",
    casterLevel: "Zauberstufe",
    breakdownSuppressed: "wirkt nicht",
    portrait: "Porträt",
  },

  actions: {
    create: "Anlegen",
    save: "Speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    edit: "Bearbeiten",
    add: "Hinzufügen",
    remove: "Entfernen",
    back: "Zurück",
    next: "Weiter",
    done: "Fertig",
    roll: "Würfeln",
    export: "Exportieren",
    import: "Importieren",
    search: "Suchen…",
    equip: "Anlegen",
    unequip: "Ablegen",
    levelUp: "Stufenaufstieg",
  },

  wizard: {
    title: "Neuer Charakter",
    steps: ["Volk", "Attribute", "Klasse", "Fertigkeiten", "Talente", "Ausrüstung", "Fertig"],
    name: "Name",
    playerName: "Spieler:in",
    hpRoll: "TP-Wurf",
    pointsLeft: "Punkte übrig",
    slotsLeft: "Slots übrig",
    standardArray: "Standardreihe (15/14/13/12/10/8)",
    rollAll: "🎲 Alle würfeln (4W6, niedrigster fällt)",
  },

  settings: {
    features: "Funktionen",
    diceEnabled: "Würfeln in der App",
    diceEnabledHint: "Aus: keine Würfel-Knöpfe am Bogen und kein Würfel-Reiter.",
    encumbrance: "Gewicht & Traglast",
    encumbranceHint: "Aus: keine Gewichtsangaben, und die Last bremst weder Bewegung noch Geschicklichkeit.",
    houseRules: "Hausregeln",
    fractional: "Fraktionale BAB/Saves (Unearthed Arcana)",
    maxHpL1: "Volle TP auf Stufe 1",
    xpPenalty: "Multiclass-EP-Strafe (RAW)",
    exportTitle: "Export / Import",
    exportAll: "Alles exportieren (JSON)",
    importFile: "JSON importieren",
    storage: "Speicher",
    persisted: "Speicher ist persistent",
    notPersisted: "Speicher NICHT garantiert persistent — Export als Backup empfohlen!",
    license: "Lizenz (OGL)",
    dataPrivacy:
      "Alle Daten liegen nur lokal auf diesem Gerät (IndexedDB). Teilen per Export/Import.",
  },

  compendium: {
    kinds: {
      race: "Völker",
      class: "Klassen",
      feat: "Talente",
      skill: "Fertigkeiten",
      spell: "Zauber",
      item: "Gegenstände",
      monster: "Monster",
      condition: "Zustände",
      spelllist: "Zauberlisten",
    } as Record<string, string>,
    sourceSrd: "SRD",
    sourceHomebrew: "Homebrew",
    empty: "Nichts gefunden.",
  },

  dice: {
    title: "Würfel",
    history: "Verlauf",
    placeholder: "z.B. 2d6+3",
    invalid: "Ungültiger Ausdruck",
  },

  hpPad: {
    title: "Trefferpunkte ändern",
    heal: "Heilen",
    temp: "Temp.",
    damage: "Schaden",
    nonlethal: "Nichttödl.",
    open: "TP ändern",
    backspace: "Zeichen löschen",
    clear: "leeren",
    errors: {
      syntax: "Ausdruck ist unvollständig",
      "divide-by-zero": "Teilung durch Null",
      overflow: "Zahl ist zu groß",
      "too-complex": "Ausdruck ist zu verschachtelt",
      empty: "",
    } as Record<string, string>,
    rounded: (exact: string) => `${exact} — Bruchteil fällt weg`,
    negative: "unter 0 — kein Effekt",
  },

  trackers: {
    title: "Zähler",
    add: "Zähler anlegen",
    hint: "Für eigene Mechaniken: Aktionspunkte, Untote vertreiben, Schicksalspunkte …",
    name: "Name",
    kind: "Art",
    kinds: { counter: "Zähler", value: "Fester Wert", roll: "Würfelwurf" } as Record<string, string>,
    value: "Wert",
    max: "Maximum (optional)",
    formula: "Würfelformel (z.B. 1d6+2)",
    reset: "Zurücksetzen",
    empty: "Noch keine Zähler. Leg einen an für Aktionspunkte & Co.",
    suggestHint: "Aus deinen Klassen ergeben sich diese Zähler:",
    suggestAdd: "anlegen",
  },

  notes: {
    sections: "Abschnitte",
    addSection: "Abschnitt anlegen",
    sectionTitle: "Titel (z.B. Gottheit, Familie, Hausregeln)",
    freeText: "Schnellnotizen",
    emptySections: "Noch keine Abschnitte — gut für Gottheit, Hintergrund oder Hausregel-Formeln.",
  },

  spells: {
    prepared: "Vorbereitet",
    known: "Bekannt",
    spellbook: "Zauberbuch",
    prepare: "Vorbereiten",
    learn: "Lernen",
    cast: "Wirken",
    rest: "Rast (Slots zurücksetzen)",
    browse: "Zauberliste durchsuchen",
    onlySpellbook: "nur Zauberbuch",
    level: "Grad",
    dc: "SG",
    noSlotsLeft: "keine Slots mehr",
    preparedHint:
      "Wirken zählt die Slots des Grads hoch — welcher konkrete Zauber verbraucht ist, merkt ihr euch wie am Tisch üblich.",
    knownLimit: (have: number, max: string) => `${have}/${max} bekannt`,
    slots: "Slots",
    addToSpellbook: "Zauberbuch erweitern",
    emptySpellbook: "Noch keine Zauber im Buch — unten aus der Klassenliste wählen.",
    noneAtLevel: "Kein Zauber dieses Grades gefunden.",
    another: "noch einmal vorbereiten",
    unprepare: "Vorbereitung lösen",
    unlearn: "Vergessen",
    removeFromSpellbook: "Aus dem Zauberbuch nehmen",
  },

  import: {
    title: "Aus Fight Club importieren",
    pick: "Fight-Club-XML wählen…",
    hint: "Exportiere in Fight Club deinen Charakter als XML und wähle die Datei hier aus. Die App rekonstruiert Volk, Klassen, Attribute, Ränge, Talente und Waffen; RK und Rettungswürfe werden per sichtbarem Ausgleichs-Modifikator auf die Originalwerte gebracht (fehlende Ausrüstung).",
    found: (n: number) => (n === 1 ? "1 Charakter gefunden" : `${n} Charaktere gefunden`),
    apply: "Übernehmen",
    applied: (n: number) => `${n} Charakter(e) übernommen.`,
    comparison: "Abgleich mit dem Original",
    matchLabel: "stimmt",
    reconciled: "ausgeglichen",
    reportedOnly: "weicht ab",
    matches: "Alle Werte stimmen mit dem Original überein.",
    noValues: "Der Export enthält keine Vergleichswerte (RK, Rettungswürfe, GAB) — nichts zu prüfen.",
    notes: "Hinweise",
    failed: "Datei konnte nicht gelesen werden",
    nothing: "Keine Charaktere in der Datei gefunden.",
  },

  levelUp: {
    title: "Stufenaufstieg",
    ready: "⬆ Bereit zum Aufstieg!",
    chooseClass: "Klasse für die neue Stufe",
    hpRoll: "TP-Wurf für diese Stufe",
    rollHp: "würfeln",
    abilityIncrease: "Attributssteigerung (alle 4 Stufen)",
    skills: "Fertigkeitspunkte verteilen",
    feats: "Neues Talent wählen",
    newSpells: "Neue Zauber lernen",
    summary: "Zusammenfassung",
    apply: "Stufe aufsteigen",
    hpDelta: "Trefferpunkte",
    newLevel: "Neue Stufe",
  },

  misc: {
    loading: "Lade…",
    seedRunning: "SRD-Kompendium wird eingerichtet…",
    noCharacters: "Noch keine Charaktere. Leg deinen ersten an!",
    confirmDelete: (name: string) => `„${name}" wirklich löschen?`,
    issues: "Hinweise",
    updateAvailable: "Update verfügbar — neu laden?",
    offlineReady: "App ist offline verfügbar.",
  },
};
